### ISSUE TITLE
I built the app, installed, registered client on Instagram, now what?

### ISSUE THREAD

**Issue by levibostian** [socioboard/i-board#1]
Hello, super excited I found this app as all of the features inside I have been looking for so I got super excited when I found this app. 

I got it imported into Android Studio, installed on my phone, registered a new client to Instagram, but it isn't working. When I register the client to my Instagram account, I have the redirect URL to my website but that will not work as my website is not programmed for this. 

Don't I have to enter in your website for the redirect URL to get working? My website server is not designed to work for this. Or is there a way to create my own API on my website to be able to handle it? 

Thanks for creating this great app!

**Comment by yousofkakhki** [comment]
+1
